// Generated by CoffeeScript 1.12.6
(function() {
  $(document).ready(function() {
    return setActiveFeature(0);
  });

  this.setActiveFeature = function(n) {
    var feat, feats, html, i, j, k, len, ref, url;
    feats = document.getElementsByClassName("feat-objects");
    url = feats[n].getElementsByClassName('video-url')[0].innerHTML;
    document.getElementById("feature-video").innerHTML = '<p><iframe frameborder="0" height="562.5" src="' + url + '" width="1000"></iframe></p>';
    for (j = 0, len = feats.length; j < len; j++) {
      feat = feats[j];
      feat.className = feat.className.replace(" active", "");
    }
    feats[n].className += " active";
    html = "";
    for (i = k = 0, ref = feats.length; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
      if (!feats[i].classList.contains("active")) {
        html += '<img src="' + feats[i].getElementsByClassName("thumbnail-url")[0].innerHTML + '" class="preview-item champ-card" onclick="setActiveFeature(' + i + ')" />';
      }
    }
    document.getElementById("preview-container").innerHTML = html;
  };

}).call(this);

//# sourceMappingURL=script.js.map
